<?php

if ($this->isActive() && $this->check()) {

        $hitCount = $this->getHitCount();
        $jssorSlides = $this->getBannerSlides();
        $jssorId = $this->getIdFromConfig();
        $jssorIndex = $this->getIndex();
        $jssorConfigId = $this->getBannerJssorId();
        $jssorSlideTransitions = $this->getBannerJssorSlideTransitions();
        $jssorSlideBreaks = $this->getBannerJssorSlideBreaks();
        $jssorSlideControls = $this->getBannerJssorSlideControls();
        $jssorMaxWidth = $this->getBannerJssorMaxWidth();
        $jssorCSS = $this->getBannerJssorCSS();
        $jssorStyle = $this->getBannerJssorStyle();
        $jssorLoadingScreen = $this->getBannerJssorLoadingScreen();
        $jssorSlidesStyle = $this->getBannerJssorSlidesStyle();
        $jssorBulletNavigator = $this->getBannerJssorBulletNavigator();
        $jssorArrowNavigator = $this->getBannerJssorArrowNavigator();
        $jssorFunction = $this->getBannerFunction();
        $jssorLayout = $this->getBannerLayout();
        $jssorOptions = $this->getBannerJssorOptions();

        // if there is only one banner or it is using the 'small' layout, don't be draggable

        if ($hitCount < 2 || $jssorLayout != 'large') {
         $jssorOptions = substr_replace($jssorOptions, '$DragOrientation:0, ', 1, 0);
        }

?>

    <script type="text/javascript">
    require([
        'jquery',
        'jssor'
    ], function ($, jssor) {
        'use strict';

        var <?php echo $jssorId ?>_slider_init = function() {

            var <?php echo $jssorId ?>_options = <?php echo $jssorOptions ?>;

            var <?php echo $jssorId ?>_SlideoTransitions = <?php echo $jssorSlideTransitions ?>;

            var <?php echo $jssorId ?>_SlideoBreaks = <?php echo $jssorSlideBreaks ?>;

            var <?php echo $jssorId ?>_SlideoControls = <?php echo $jssorSlideControls ?>;

            var <?php echo $jssorId ?>_slider = new $JssorSlider$("<?php echo $jssorId ?>", <?php echo $jssorId ?>_options);

            var MAX_WIDTH = <?php echo $jssorMaxWidth ?>;

            function ScaleSlider() { <?php echo $jssorFunction ?> }

            ScaleSlider();

            $Jssor$.$AddEvent(window, "load", ScaleSlider);
            $Jssor$.$AddEvent(window, "resize", ScaleSlider);
            $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
        };
        <?php echo $jssorId ?>_slider_init();

        $(document).ready(function() {
            window.setTimeout(showOverlay, <?php echo $this->getOverlayTimeout(); ?>);
        });

        function showOverlay() {
            $(".bxBannerOverlay").fadeIn("slow");
        }

        $('#bxBannerOverlayExitButton').on('click', function(){
          $('.bxBannerOverlay').hide();
        });

        var idleTime = 0;
        var frequency = 0;
        var mouseLocation = 'in';

        // Increase the idle time counter every second.
        setInterval(timerIncrement, 1000); // 1 second

        // Start action when the mouse leaves the window
        document.addEventListener('mouseleave', function(){

          // Increase the frequency counter when the mouse leaves the window
          frequency++;

          // set state of mouse to out
          mouseLocation = 'out';

          //Zero the idle timer on mouse movement.
          $(this).mousemove(function (e) {
              idleTime = 0;
          });
          $(this).click(function (e) {
              idleTime = 0;
          });

        });

        // When Mouse enters window, reset the counter and set state of mouse on 'in'
        document.addEventListener('mouseenter', function(){
          idleTime = 0;
          mouseLocation = 'in';
        });

        // Increase the timer and display the overlay after x seconds
        function timerIncrement() {
          // check if the mouse is out of the window
          if (mouseLocation === 'out') {
          idleTime++;

            // check if the idleTime is below the defined time
            if (idleTime > <?php echo $this->getOverlayExitIntendTimeout(); ?>) { //idleTime before showOverlay

              // check how many times the overlay can appear when the mous leaves the screen (0 means never)
              if (<?php echo $this->getOverlayFrequency(); ?> !== 0 && frequency <= <?php echo $this->getOverlayFrequency(); ?>) {
                showOverlay();
              }
            }
          }
        }

      });


    </script>

    <style>

    <?php echo $jssorCSS ?>

    </style>

    <div id="<?php echo $jssorId ?>" class="bxBannerOverlay"  style="<?php echo $jssorStyle ?>">

      <button type="button" id="bxBannerOverlayExitButton" class="bxBannerOverlay">&#x2715;</button>

    <?php echo $jssorLoadingScreen ?>

        <div data-u="slides" style="<?php echo $jssorSlidesStyle ?>">

            <?php

                foreach($jssorSlides as $bannerSlideId => $values ) {

                    echo $values['div'];

                }

            ?>

        </div>

        <?php if ($hitCount > 1 && $jssorLayout == 'large'){

          // if there is more than one and the layout is not 'small', add the bullet- & arrow navigators

          echo $jssorBulletNavigator;
          echo $jssorArrowNavigator;

        }; ?>

      </div>

      <?php if ($this->withLightboxEffect() == 'true') { ?>

        <div class="bxBannerOverlay" id="bxOverlayShadow"></div>

      <?php } ?>

<?php } ?>
