<?php

  $hitCount = $this->getHitCount();

if ($this->isActive() && $this->check()) {

        $jssorSlides = $this->getBannerSlides();
        $jssorId = $this->getBannerJssorId();
        $jssorSlideTransitions = $this->getBannerJssorSlideTransitions();
        $jssorSlideBreaks = $this->getBannerJssorSlideBreaks();
        $jssorSlideControls = $this->getBannerJssorSlideControls();
        $jssorOptions = $this->getBannerJssorOptions();
        $jssorMaxWidth = $this->getBannerJssorMaxWidth();
        $jssorCSS = $this->getBannerJssorCSS();
        $jssorStyle = $this->getBannerJssorStyle();
        $jssorLoadingScreen = $this->getBannerJssorLoadingScreen();
        $jssorSlidesStyle = $this->getBannerJssorSlidesStyle();
        $jssorBulletNavigator = $this->getBannerJssorBulletNavigator();
        $jssorArrowNavigator = $this->getBannerJssorArrowNavigator();
        $jssorFunction = $this->getBannerFunction();


?>

    <script type="text/javascript">
    require([
        'jquery',
        'jssor'
    ], function ($, jssor) {
        'use strict';

        var <?php echo $jssorId ?>_slider_init = function() {

            var hitCount = <?php echo $hitCount ?>;

            if (hitCount < 2) {

              var jssor_1_options = { $DragOrientation:0 };

            } else {

              var jssor_1_options = <?php echo $jssorOptions ?>;

            }

            var jssor_1_SlideoTransitions = <?php echo $jssorSlideTransitions ?>;

            var jssor_1_SlideoBreaks = <?php echo $jssorSlideBreaks ?>;

            var jssor_1_SlideoControls = <?php echo $jssorSlideControls ?>;

            var jssor_1_slider = new $JssorSlider$(<?php echo $jssorId ?>, jssor_1_options);

            var MAX_WIDTH = <?php echo $jssorMaxWidth ?>;

            function ScaleSlider() { <?php echo $jssorFunction ?> }

            ScaleSlider();

            $Jssor$.$AddEvent(window, "load", ScaleSlider);
            $Jssor$.$AddEvent(window, "resize", ScaleSlider);
            $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
        };
        <?php echo $jssorId ?>_slider_init();
      }
    );


    </script>

    <style>

    <?php echo $jssorCSS ?>

    </style>

    <div id="<?php echo $jssorId ?>" style="<?php echo $jssorStyle ?>">

    <?php echo $jssorLoadingScreen ?>

        <div data-u="slides" style="<?php echo $jssorSlidesStyle ?>">

            <?php

                foreach($jssorSlides as $bannerSlideId => $values ) {

                    echo $values['div'];
                }

            ?>

        </div>

        <?php if ($hitCount > 1){

          echo $jssorBulletNavigator;
          echo $jssorArrowNavigator;

        }; ?>

    </div>

<?php

}

?>
