<?php 
    if ($this->isActive()) {
?>    
<script src="https://www.jssor.com/script/jssor.slider-26.1.5.min.js" type="text/javascript"></script>
<script type="text/javascript">
    <?php echo $this->getBannerJssorId() ?>_slider_init = function() {

        var jssor_1_SlideoTransitions = <?php echo $this->getBannerJssorSlideTransitions() ?>

        var jssor_1_options = <?php echo $this->getBannerJssorOptions() ?>;

        var jssor_1_slider = new $JssorSlider$(<?php echo $this->getBannerJssorId() ?>, jssor_1_options);

        var MAX_WIDTH = <?php echo $this->getBannerJssorMaxWidth() ?>;

        function ScaleSlider() {
            var containerElement = jssor_1_slider.$Elmt.parentNode;
            var containerWidth = containerElement.clientWidth;

            if (containerWidth) {

                var expectedWidth = Math.min(MAX_WIDTH || containerWidth, containerWidth);

                jssor_1_slider.$ScaleWidth(expectedWidth);
            }
            else {
                window.setTimeout(ScaleSlider, 30);
            }
        }

        ScaleSlider();

        $Jssor$.$AddEvent(window, "load", ScaleSlider);
        $Jssor$.$AddEvent(window, "resize", ScaleSlider);
        $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
        /*#endregion responsive code end*/
    };
</script>
<style>
    <?php echo $this->getBannerJssorCSS() ?>
</style>
<div id="<?php echo $this->getBannerJssorId() ?>">

    <?php echo $this->getBannerJssorLoadingScreen() ?>
    
    <div data-u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:1300px;height:500px;overflow:hidden;">

        <?php 

            foreach($this->getBannerSlides() as $bannerSlideId => $values ) {

                echo $values['div'];
            }

        ?>
        <a data-u="any" href="https://www.jssor.com" style="display:none">bootstrap carousel</a>
    </div>

    <?php echo $this->getBannerJssorBulletNavigator() ?>
    <?php echo $this->getBannerJssorArrowNavigator() ?>
    
</div>
<script type="text/javascript"><?php echo $this->getBannerJssorId() ?>_slider_init();</script>
<?php } ?>