<?php
/**
 * @see \Boxalino\Intelligence\Block\Block
 */
?>
<?php if ($this->canBeDisplayed()):?>
    <script type="text/x-magento-init">
    {
         "*":{
            "bxOverlay": {
                "basketTotal":<?php echo $this->getGrandTotal(); ?>,
                "parameters":<?php echo $this->getOverlayJsParameters(); ?>,
                "controllerUrl":"<?php echo $this->getControllerUrl(); ?>",
                "lang":"<?php echo $this->getLanguage(); ?>"
            }
        }
    }
    </script>
    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            'use strict';

            <?php echo $this->getOverlayBehaviorJs(); ?>
        });
    </script>

    <div class="bxOverlay container">
        <?php echo $this->getOverlayBlock()->toHtml();?>
    </div>

    <?php if ($this->withLightboxEffect() == 'true'): ?>
        <div class="bxOverlay shadow" id="bxOverlayShadow"></div>
    <?php endif; ?>

<?php endif; ?>
