<?php
/**
 * Product view template
 *
 * @see \Boxalino\Intelligence\Block\SearchMessage
 */
?>

<?php if ($this->isActive()):?>
    <?php
    if (!empty($this->getSearchMessageTitle())) {
        echo "<style>.page-title-wrapper{display: none !important;}</style>"; //if there is a searchmessage, hide the page title
    }

    switch ($this->getDisplayType()) {
        case 'main-image': ?>
            <div class="bx-search-message main-image <?php echo $this->getGeneralCssClass();?>">
                <span>
                    <strong class="bx-search-message-title <?php echo $this->getTitleCssClass();?>" style="<?php echo $this->getTitleStyle();?>"><?php echo $this->getSearchMessageTitle();?></strong>
                </span>
                <span class="bx-search-message-main-image <?php echo $this->getMainImageCssClass();?>">
                    <img src="<?php echo $this->getMainImage(); ?>"/>
                </span>
            </div>
            <?php break;

        case 'main-image-link':
            ?>
            <div class="bx-search-message main-image-link <?php echo $this->getGeneralCssClass();?>">
                <a href="<?php echo $this->getSearchMessageLink(); ?>" class="bx-search-message-link <?php echo $this->getLinkCssClass();?>">
                    <span>
                        <strong class="bx-search-message-title <?php echo $this->getTitleCssClass();?>" style="<?php echo $this->getTitleStyle();?>"><?php echo $this->getSearchMessageTitle(); ?></strong>
                    </span>
                    <span class="bx-search-message-main-image <?php echo $this->getMainImageCssClass();?>">
                        <img src="<?php echo $this->getMainImage(); ?>"/>
                    </span>
                </a>
            </div>
            <?php break;

        case 'side-image':
            ?>
            <div class="bx-search-message side-image <?php echo $this->getGeneralCssClass();?>">
                <div class="bx-search-message-container-left">
                    <p class="bx-search-message-title <?php echo $this->getTitleCssClass();?>" style="<?php echo $this->getTitleStyle();?>">
                        <?php echo $this->getSearchMessageTitle(); ?>
                    </p>
                    <p class="info bx-search-message-description <?php echo $this->getDescriptionCssClass();?>" style="<?php echo $this->getDescriptionStyle();?>">
                        <?php echo $this->getDescription(); ?>
                    </p>
                </div>
                <div class="bx-search-message-container-right">
                    <div class="bx-search-message-side-image <?php echo $this->getSideImageCssClass();?>">
                        <img src="<?php echo $this->getSideImage(); ?>"/>
                    </div>
                </div>
            </div>
            <?php break;

        case 'side-image-link': ?>
            <div class="bx-search-message side-image-link <?php echo $this->getGeneralCssClass();?>">
                <div class="bx-search-message-container-left">
                    <p class="bx-search-message-title <?php echo $this->getTitleCssClass();?>" style="<?php echo $this->getTitleStyle();?>">
                        <?php echo $this->getSearchMessageTitle(); ?>
                    </p>
                    <a href="<?php echo $this->getSearchMessageLink(); ?>" class="bx-search-message-link <?php echo $this->getLinkCssClass();?>">
                        <p class="info bx-search-message-description bx-side-image-link <?php $this->getDescriptionCssClass();?>" style="<?php echo $this->getDescriptionStyle();?>">
                            <?php echo $this->getDescription(); ?>
                        </p>
                    </a>
                </div>
                <div class="bx-search-message-container-right">
                    <div class="bx-search-message-side-image <?php echo $this->getSideImageCssClass();?>">
                        <img src="<?php echo $this->getSideImage();?>"/>
                    </div>
                </div>
            </div>
            <?php break;

        case 'no-image': ?>
            <div class="bx-search-message no-image <?php echo $this->getGeneralCssClass();?>">
                <p class="bx-search-message-title <?php echo $this->getTitleCssClass();?>" style="<?php echo $this->getTitleStyle();?>">
                    <?php echo $this->getSearchMessageTitle(); ?>
                </p>
                <p class="info bx-search-message-description <?php $this->getDescriptionCssClass();?>" style="<?php echo $this->getDescriptionStyle();?>">
                    <?php echo $this->getDescription(); ?>
                </p>
            </div>
            <?php break;

        case 'no-image-link': ?>
            <div class="bx-search-message no-image-link <?php echo $this->getGeneralCssClass();?>">
                <p class="bx-search-message-title <?php echo $this->getTitleCssClass();?>" style="<?php echo $this->getTitleStyle();?>">
                    <?php echo $this->getSearchMessageTitle(); ?>
                </p>
                <a href="<?php echo $this->getSearchMessageLink(); ?>" class="bx-search-message-link <?php echo $this->getLinkCssClass();?>">
                    <p class="info bx-search-message-description <?php $this->getDescriptionCssClass();?>" style="<?php echo $this->getDescriptionStyle();?>">
                        <?php echo $this->getDescription(); ?>
                    </p>
                </a>
            </div>
            <?php break;

        default:
            # code...
            break;
    } ?>
<?php endif;?>