<?php
  if ($this->isActive()) {
    $response = $this->getResponse();

    switch ($response->getSearchMessageDisplayType()) {
      case 'main-image': ?>
        <div class="bx-main-image-search-message">
          <span>
            <strong class="bx-main-image-search-message-title"><?php echo $response->getSearchMessageTitle(); ?></strong>
          </span>
          <span class="bx-main-image-search-message-main-image">
            <img src="<?php echo $response->getSearchMessageMainImage(); ?>"/>
          </span>
        </div>
      <?php break;

      case 'main-image-link':?>
        <div class="bx-main-image-link-search-message">
          <a href="<?php echo $response->getSearchMessageLink(); ?>" class="bx-main-image-link-search-message-link">
            <span>
              <strong class="bx-main-image-link-search-message-title"><?php echo $response->getSearchMessageTitle(); ?></strong>
            </span>
            <span class="bx-main-image-link-search-message-main-image">
              <img src="<?php echo $response->getSearchMessageMainImage(); ?>"/>
            </span>
          </a>
        </div>
      <?php break;

      case 'side-image':?>
        <div class="bx-side-image-search-message">
          <div class="bx-side-image-search-message-container-left">
            <p class="bx-side-image-search-message-title">
              <?php echo $response->getSearchMessageTitle(); ?>
            </p>
            <p class="info bx-side-image-search-message-description">
              <?php echo $response->getSearchMessageDescription(); ?>
            </p>
            </div>
            <div class="bx-side-image-search-message-container-right">
              <div class="bx-side-image-search-message-side-image">
                <img src="<?php echo $response->getSearchMessageSideImage(); ?>"/>
              </div>
          </div>
        </div>
      <?php break;

      case 'side-image-link': ?>
        <div class="bx-side-image-link-search-message">
          <div class="bx-side-image-link-search-message-container-left">
            <p class="bx-side-image-link-search-message-title">
              <?php echo $response->getSearchMessageTitle(); ?>
            </p>
          <a href="<?php echo $response->getSearchMessageLink(); ?>" class="bx-side-image-link-search-message-link">
            <p class="info bx-ide-image-link-search-message-description">
                <?php echo $response->getSearchMessageDescription(); ?>
            </p>
          </a>
          </div>
          <div class="bx-side-image-link-search-message-container-right">
            <div class="bx-side-image-link-search-message-side-image">
              <img src="<?php echo $response->getSearchMessageSideImage(); ?>"/>
            </div>
          </div>
        </div>
      <?php break;

      case 'no-image': ?>
        <div class="bx-no-image-search-message">
          <p class="bx-no-image-search-message-title">
            <?php echo $response->getSearchMessageTitle(); ?>
          </p>
          <p class="info bx-no-image-search-message-description">
            <?php echo $response->getSearchMessageDescription(); ?>
          </p>
        </div>
      <?php break;

      case 'no-image-link': ?>
        <div class="bx-no-image-link-search-message">
          <p class="bx-no-image-link-search-message-title">
            <?php echo $response->getSearchMessageTitle(); ?>
          </p>
          <a href="<?php echo $response->getSearchMessageLink(); ?>" class="bx-no-image-link-search-message-link">
            <p class="info bx-no-image-link-search-message-description">
              <?php echo $response->getSearchMessageDescription(); ?>
            </p>
          </a>
        </div>
      <?php break;

      default:
      # code...
      break;
    }
  }
?>
