<?php
$image_desktop = $this->getLocalizedValue($this->getData('image_desktop'));
$image_mobile = $this->getLocalizedValue($this->getData('image_mobile'));
$image_link_path = $this->getLocalizedValue($this->getData('image_link_path'));
$image_alt_text = $this->getLocalizedValue($this->getData('image_alt_text'));
?>

    <a href="<?php echo $image_link_path ?>">
        <img src="<?php echo $image_desktop ?>" alt="<?php echo $image_alt_text ?>" />
    </a>

<?php
//get sub-renderings of this view element
$subRenderings = $this->getSubRenderings();
foreach ($subRenderings as $subRendering) {
    echo $this->renderVisualElement($subRendering['visualElement']);
}
?>