<?php
$bannerData = $this->bxGetBanner();
$hitCount = $bannerData['hitCount'];
$jssorSlides = $bannerData['bannerSlides'];
$jssorId = $this->getData('jssorID');
$jssorIndex = $this->getData('jssorIndex');
$jssorConfigId = $bannerData['bannerId'];
$jssorSlideTransitions = $bannerData['bannerTransitions'];
$jssorSlideBreaks = $bannerData['bannerBreaks'];
$jssorSlideControls = $bannerData['bannerControls'];
$jssorMaxWidth = $bannerData['bannerMaxWidth'];
//$jssorCSS = $bannerData['bannerCSS'];
//$jssorStyle = $bannerData['bannerStyle'];
$jssorLoadingScreen = $bannerData['bannerLoadingScreen'];
//$jssorSlidesStyle = $bannerData['bannerSlidesStyle'];
$jssorBulletNavigator = $bannerData['bannerBulletNavigator'];
$jssorArrowNavigator = $bannerData['bannerArrowNavigator'];
$jssorFunction = $bannerData['bannerFunction'];
$jssorLayout = $bannerData['bannerLayout'];
$jssorOptions = $bannerData['bannerOptions'];

// if there is only one banner or it is using the 'small' layout, don't be draggable
if ($hitCount<2 || (!empty($jssorLayout) && $jssorLayout != 'large')) {
    $jssorOptions = substr_replace(preg_replace("/\s+/","",$jssorOptions), '$DragOrientation:0, ', 1, 0);
}
?>
<?php if(!empty($jssorSlides)) :?>
    <script type="text/javascript">
        require([
                'jquery',
                'jssor'
            ], function ($, jssor) {
                'use strict';
                var <?php echo $jssorId ?>_slider_init = function() {
                    var <?php echo $jssorId ?>_options = <?php echo $jssorOptions ?>;
                    var <?php echo $jssorId ?>_SlideoTransitions = <?php echo $jssorSlideTransitions ?>;
                    var <?php echo $jssorId ?>_SlideoBreaks = <?php echo $jssorSlideBreaks ?>;
                    var <?php echo $jssorId ?>_SlideoControls = <?php echo $jssorSlideControls ?>;
                    var <?php echo $jssorId ?>_slider = new $JssorSlider$("<?php echo $jssorId ?>", <?php echo $jssorId ?>_options);
                    var MAX_WIDTH = <?php echo $jssorMaxWidth ?>;
                    function ScaleSlider() { <?php echo $jssorFunction ?> }
                    ScaleSlider();
                    $Jssor$.$AddEvent(window, "load", ScaleSlider);
                    $Jssor$.$AddEvent(window, "resize", ScaleSlider);
                    $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
                };
                <?php echo $jssorId;?>_slider_init();
            }
        );
    </script>
    <div id='<?php echo $jssorId;?>' class="bxNarrativeBannerJssor">
        <div data-u="loading" class="jssorl-009-spin"></div>
        <div data-u="slides" class="bxNarrativeBannerJssorSlides">
            <?php
            foreach($jssorSlides as $bannerSlideId => $values ) {
                echo $values['div'];
            }
            ?>
        </div>
        <?php if ($hitCount > 1 && $jssorLayout == 'large'): ?>
            // if there is more than one and the layout is not 'small', add the bullet- & arrow navigators
            <div data-u="navigator" class="jssorb032 bxBannerJssorBulletNavigator" data-autocenter="1" data-scale="0.5" data-scale-bottom="0.75">
                <div data-u="prototype" class="i">
                    <svg viewbox="0 0 16000 16000">
                        <circle class="b" cx="8000" cy="8000" r="5800"></circle>
                    </svg>
                </div>
            </div>
            <div data-u="arrowleft" class="jssora051 bxBannerJssorArrowLeft" data-autocenter="2" data-scale="0.75" data-scale-left="0.75">
                <svg viewbox="0 0 16000 16000">
                    <polyline class="a" points="11040,1920 4960,8000 11040,14080 "></polyline>
                </svg>
            </div>
            <div data-u="arrowright" class="jssora051 bxBannerJssorArrowRight" data-autocenter="2" data-scale="0.75" data-scale-right="0.75">
                <svg viewbox="0 0 16000 16000">
                    <polyline class="a" points="4960,1920 11040,8000 4960,14080 "></polyline>
                </svg>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>