<li class="item product product-item blogArticlePost">

  <?php $blogArticle = $block->getBlogArticle();?>

  <figure>
    <a href="<?php echo $blogArticle[$this->getLinkFieldName()] ?>">
      <img
        width="<?php echo $this->getBlogArticleImageWidth() ?>"
        height="<?php echo $this->getBlogArticleImageHeight() ?>"
        src="<?php echo $blogArticle[$this->getMediaUrlFieldName()] ?>"
       >
    </a>
  </figure>

  <div class="blogArticleTextArea">

  <h4 class="blogArticleHeader">
    <a href="<?php echo $blogArticle[$this->getLinkFieldName()] ?>">
      <?php echo $this->escapeHtml($blogArticle['title']); ?>
    </a>
  </h4>

  </div>
</li>
