<?php
$productCollection = $this->getItems();
$widget = $this->getData('widget');
$image = 'upsell_products_list';
if($productCollection):
    ?>
    <div class="block <?php echo $widget ?>">
        <?php if ($this->getRecommendationTitle()): ?><div class="block-title title"><strong><?php echo $block->escapeHtml($this->getRecommendationTitle()) ?></strong></div><?php endif; ?>
        <div class="block-content content">
            <div class="products wrapper grid products-grid products-<?php echo $widget; ?>">
                <ol class="products list items product-items">
                    <?php foreach($productCollection as $product): ?>
                        <li class="item product product-item">
                            <div class="product-item-info ">
                                <a href="<?php echo $block->getProductUrl($product); ?>" class="product photo product-item-photo">
                                    <?php echo $block->getImage($product, $image)->toHtml(); ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           title="<?php echo $block->escapeHtml($product->getName()); ?>"
                                           href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($product) ?>">
                                            <?php echo $block->escapeHtml($product->getName()) ?>
                                        </a>
                                    </strong>

                                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($product); ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
    </div>
<?php endif; ?>