<?php $config = $this->getData('bx_config');
?>

<?php
if(isset($config['search_message_display_type'])) :

if (isset($config['search_message_title'])) {
  echo "<style>.page-title-wrapper{display: none !important;}</style>"; //if there is a searchmessage, hide the page title
}

?>

<?php
    switch ($config['search_message_display_type']) {
        case 'main-image': ?>
            <div class="bx-main-image-search-message">
                <span>
                    <strong class="bx-main-image-search-message-title">
                        <?php echo isset($config['search_message_title']) ? $config['search_message_title'] : '';?>
                    </strong>
                </span>
                <span class="bx-main-image-search-message-main-image">
                    <img src="<?php echo isset($config['search_message_main_image']) ? $config['search_message_main_image'] : ''; ?>"/>
                </span>
            </div>
            <?php break;

        case 'main-image-link': ?>
            <div class="bx-main-image-link-search-message">
              <a href="<?php echo isset($config['search_message_link']) ? $config['search_message_link'] : ''; ?>" class="bx-main-image-link-search-message-link">
                <span>
                    <strong class="bx-main-image-link-search-message-title">
                        <?php echo isset($config['search_message_title']) ? $config['search_message_title'] : '';?>
                    </strong>
                </span>
                <span class="bx-main-image-link-search-message-main-image">
                  <img src="<?php echo isset($config['search_message_main_image']) ? $config['search_message_main_image'] : ''; ?>"/>
                </span>
              </a>
            </div>
            <?php break;

        case 'side-image':?>
            <div class="bx-side-image-search-message">
                <div class="bx-side-image-search-message-container-left">
                    <p class="bx-side-image-search-message-title">
                        <?php echo isset($config['search_message_title']) ? $config['search_message_title'] : '';?>
                    </p>
                    <p class="info bx-side-image-search-message-description">
                        <?php echo isset($config['search_message_description']) ? $config['search_message_description'] : ''; ?>
                    </p>
                </div>
                <div class="bx-side-image-search-message-container-right">
                    <div class="bx-side-image-search-message-side-image">
                        <img src="<?php echo isset($config['search_message_side_image']) ? $config['search_message_side_image'] : ''; ?>"/>
                    </div>
                </div>
            </div>
            <?php break;

        case 'side-image-link': ?>
            <div class="bx-side-image-link-search-message">
                <div class="bx-side-image-link-search-message-container-left">
                    <p class="bx-side-image-link-search-message-title">
                        <?php echo isset($config['search_message_title']) ? $config['search_message_title'] : '';?>
                    </p>
                    <a href="<?php echo isset($config['search_message_link']) ? $config['search_message_link'] : ''; ?>" class="bx-side-image-link-search-message-link">
                        <p class="info bx-ide-image-link-search-message-description">
                            <?php echo isset($config['search_message_description']) ? $config['search_message_description'] : ''; ?>
                        </p>
                    </a>
                </div>
                <div class="bx-search-message-container-right">
                    <div class="bx-side-image-link-search-message-container-right">
                        <div class="bx-side-image-link-search-message-side-image">
                            <img src="<?php echo isset($config['search_message_side_image']) ? $config['search_message_side_image'] : ''; ?>"/>
                        </div>
                    </div>
                </div>

            </div>
            <?php break;

        case 'no-image': ?>
            <div class="bx-no-image-search-message">
                <p class="bx-no-image-search-message-title">
                    <?php echo isset($config['search_message_title']) ? $config['search_message_title'] : '';?>
                </p>
                <p class="info bx-no-image-search-message-description">
                    <?php echo isset($config['search_message_description']) ? $config['search_message_description'] : ''; ?>
                </p>
            </div>
            <?php break;

        case 'no-image-link': ?>
            <div class="bx-no-image-link-search-message">
                <p class="bx-no-image-link-search-message-title">
                    <?php echo isset($config['search_message_title']) ? $config['search_message_title'] : '';?>
                </p>
                <a href="<?php echo isset($config['search_message_link']) ? $config['search_message_link'] : ''; ?>" class="bx-no-image-link-search-message-link">
                    <p class="info bx-no-image-link-search-message-description">
                        <?php echo isset($config['search_message_description']) ? $config['search_message_description'] : ''; ?>
                    </p>
                </a>
            </div>
            <?php break;
        default:
            break;
    }
endif;
?>
<?php
//get sub-renderings of this view element
$subRenderings = $this->getSubRenderings();
foreach ($subRenderings as $subRendering):
    echo $this->renderVisualElement($subRendering['visualElement']); ?>
<?php endforeach ?>
