<div class="bx-top-message">
    <div class="title">
        <a href="<?php echo $this->getLocalizedValue($this->getData('title_link'));?>">
            <h2><?php echo $this->getLocalizedValue($this->getData('title'));?></h2>
        </a>
    </div>
    <div class="description">
        <span><?php echo $this->getLocalizedValue($this->getData('description'));?></span>
    </div>
    <div class="image">
        <img src="<?php echo $this->getLocalizedValue($this->getData('image_url'));?>" />
    </div>
</div>
