<?php
    $om = \Magento\Framework\App\ObjectManager::getInstance();
    $data = $om->get("\Boxalino\Intelligence\Helper\Data");
    if(!$data->isEnabledOnLayer($block->getLayer())):
?>
<?php include ($block->getTemplateFile('Magento_LayeredNavigation::layer/view.phtml')); ?>
<?php else: ?>
    <?php if ($block->canShowBlock()): ?>
        <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
            <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
            <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */ echo $filtered; ?>">
                <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
            </div>
            <div class="block-content filter-content">
                <?php echo $block->getChildHtml('state') ?>
                <?php if ($block->getLayer()->getState()->getFilters()): ?>
                    <div class="block-actions filter-actions">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                    </div>
                <?php endif; ?>
                <?php
                    $wrapOptions = false;
                    $filters = $block->getFilters();
                    $expanded = array();
                    foreach($filters as $index => $filter){
                        $bxFacets = isset($bxFacets) ? $bxFacets : $filter->getBxFacets();
                        if ($bxFacets->isFacetExpanded($filter->getFieldName(), false)) $expanded[] = $index;
                    }
                ?>
                <?php foreach ($filters as $filter): ?>
                    <?php $bxFacets = isset($bxFacets) ? $bxFacets : $filter->getBxFacets();?>
                    <?php if ($filter->getItemsCount()): ?>
                        <?php if (!$wrapOptions): ?>
                            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shopping Options') ?></strong>
                            <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": <?php echo json_encode($expanded); ?>, "multipleCollapsible": true}}'>
                        <?php  $wrapOptions = true; endif; ?>
                        <div data-role="collapsible" class="filter-options-item">
                            <div data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></div>
                            <div data-role="content" class="filter-options-content">
                            <?php if($filter->getFieldName() == 'discountedPrice'): ?>
                                <div id="bxslider"></div>
                                <span id="slider-snap-value-lower"></span>
                                <span id="slider-snap-value-upper"></span>
                                <?php echo $this->getLayout()->createBlock("Boxalino\Intelligence\Block\Slider")->setTemplate("Boxalino_Intelligence::slider.phtml")->toHtml();?>
                            <?php else: ?>
                                <?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?>
                            <?php endif; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>
                    </div>
                <?php else: ?>
                    <script>
                        require([
                            'jquery'
                        ], function ($) {
                            $('#layered-filter-block').addClass('filter-no-options');
                        });
                    </script>
                <?php endif; ?>
            </div>
        </div>
        <script>
            require([
                'jquery'
            ], function($) {
                $(".show-more-values").on('click', function () {
                    var header = $(this);
                    var content = header.parent().find('.hidden-items');
                    content.slideToggle(500, function () {
                        header.text(function () {
                            return content.is(":visible") ? "<?php echo __('less values');?>" : "<?php echo __('more values');?>";
                        });
                    });
                });
            });
        </script>
    <?php endif; ?>
<?php endif; ?>

