<?php
$subRenderings = $this->getSubRenderings();
$index = 0;
$viewMode = $this->getData('list_grid');
?>
<div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?> bx-narrative"
     data-bx-variant-uuid="<?php echo $this->getRequestUuid();?>" data-bx-narrative-name="products-list"
     data-bx-narrative-group-by="<?php echo $this->getRequestGroupBy();?>"
    >
    <ol class="products list items product-items">
        <?php foreach ($subRenderings as  $subRendering): ?>
            <?php
            $additional_parameter = $this->getAdditionalParameters($subRendering['visualElement'], $index);
            echo $this->renderVisualElement($subRendering['visualElement'], $additional_parameter);
            $index++;
            ?>
        <?php endforeach; ?>
    </ol>
</div>
