<?php
$bannerData = $this->bxGetBanner($this->getP13nHelper()->getOverlayBannerChoice());
$hitCount = $bannerData['hitCount'];
$jssorSlides = $bannerData['bannerSlides'];
$jssorId = $bannerData['bannerId'];
$jssorSlideTransitions = $bannerData['bannerTransitions'];
$jssorSlideBreaks = $bannerData['bannerBreaks'];
$jssorSlideControls = $bannerData['bannerControls'];
$jssorMaxWidth = $bannerData['bannerMaxWidth'];
$jssorFunction = $bannerData['bannerFunction'];
$jssorLayout = $bannerData['bannerLayout'];

$jssorOptions = $bannerData['bannerOptions'];

// if there is only one banner or it is using the 'small' layout, don't be draggable
if ($hitCount < 2 || $jssorLayout != 'large') {
    $jssorOptions = substr_replace($jssorOptions, '$DragOrientation:0, ', 1, 0);
}
?>
<script type="text/javascript">
    require([
            'jquery',
            'jssor'
        ], function ($, jssor) {
            'use strict';
            var bannerOverlay_slider_init = function() {
                var bannerOverlay_options = <?php echo $jssorOptions ?>;
                var bannerOverlay_SlideoTransitions = <?php echo $jssorSlideTransitions ?>;
                var bannerOverlay_SlideoBreaks = <?php echo $jssorSlideBreaks ?>;
                var bannerOverlay_SlideoControls = <?php echo $jssorSlideControls ?>;
                var bannerOverlay_slider = new $JssorSlider$("bannerOverlay", bannerOverlay_options);
                var MAX_WIDTH = <?php echo $jssorMaxWidth ?>;
                function ScaleSlider() { <?php echo $jssorFunction ?> }
                ScaleSlider();
                $Jssor$.$AddEvent(window, "load", ScaleSlider);
                $Jssor$.$AddEvent(window, "resize", ScaleSlider);
                $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
            };
            bannerOverlay_slider_init();
        }
    );
</script>

<div class="bxOverlay" style="display: none;">
    <div class="bxOverlayJssor" id="bannerOverlay">
        <button  class="bxOverlayJssorExitButton" type="button">
            &#x2715;
        </button>
        <div data-u="loading" class="jssorl-009-spin"></div>
        <div data-u="slides" class="bxOverlayJssorSlides">
            <?php
            foreach($jssorSlides as $bannerSlideId => $values ) {
                echo $values['div'];
            }
            ?>
        </div>
        <?php if ($hitCount > 1 && $jssorLayout == 'large'){
            ?>
            <div data-u="navigator" class="jssorb032" data-autocenter="1" data-scale="0.5" data-scale-bottom="0.75">
                <div data-u="prototype" class="i">
                    <svg viewbox="0 0 16000 16000">
                        <circle class="b" cx="8000" cy="8000" r="5800"></circle>
                    </svg>
                </div>
            </div>
            <div data-u="arrowleft" class="jssora051 bxOverlayJssorArrowLeft" data-autocenter="2" data-scale="0.75" data-scale-left="0.75">
                <svg viewbox="0 0 16000 16000">
                    <polyline class="a" points="11040,1920 4960,8000 11040,14080 "></polyline>
                </svg>
            </div>
            <div data-u="arrowright" class="jssora051 bxOverlayJssorArrowRight" data-autocenter="2" data-scale="0.75" data-scale-right="0.75">
                <svg viewbox="0 0 16000 16000">
                    <polyline class="a" points="4960,1920 11040,8000 4960,14080 "></polyline>
                </svg>
            </div>
        <?php
        };
        ?>
    </div>
</div>
