<?php
$bxVisualElement = $this->getData('bxVisualElement');
foreach ($bxVisualElement['parameters'] as $parameter) {
    if ($parameter['name'] == 'jsParams') {
        $jsonParams = json_decode($parameter['values'][0], true);
    }
}
$bxNewsletterBackgroundImage = $this->getLocalizedValue($jsonParams['newsletterBackgroundImage']);
$bxNewsletterTitle = $this->getLocalizedValue($jsonParams['newsletterTitle']);
$bxNewsletterText = $this->getLocalizedValue($jsonParams['newsletterText']);

if (empty($bxNewsletterBackgroundImage)) {
    $bxNewsletterBackgroundImage = 'Not defined';
}
if (empty($bxNewsletterTitle)) {
    $bxNewsletterTitle = 'Not defined';
}
if (empty($bxNewsletterText)) {
    $bxNewsletterText = 'Not defined';
}
?>

<div class="bxOverlay bxOverlay-content" style="display: none;">
    <div class="bxOverlayNewsletter">
        <form id="bxOverlayNewlsetterForm" action="#" method="get">
            <button id="bxOverlayExitButton" type="button">
                &#x2715;
            </button>

            <img id="bxOverlayNewsletterBackgroundImage" src="<?php echo $bxNewsletterBackgroundImage; ?>"/>
            <div id="bxOverlayNewsletterTitle">
                <?php echo $bxNewsletterTitle; ?>
            </div>

            <div id="bxOverlayNewsletterText">
                <?php echo $bxNewsletterText; ?>
            </div>

            <input type="text" id="bxOverlayNewsletterInput" name="email"/>
            <input type="submit" id="bxOverlayNewsletterSubmit" placeholder="Ihre E-Mail Adresse"/>
            <div id="bxNewsletterImage"></div>
        </form>
    </div>
</div>

