<?php
/**
 * @block Boxalino\Intelligence\Block\Journey\Product\ProductList
 */
?>
<div class="bxOverlay bxOverlay-content" style="display: none;">
    <div class="bxOverlayProductsMain">
        <div class="bxOverlayProducts">
            <?php
            $bxVisualElement = $this->getData('bxVisualElement');
            foreach ($bxVisualElement['parameters'] as $parameter) {
                if ($parameter['name'] == 'jsParams') {
                    $jsonParams = json_decode($parameter['values'][0], true);
                }
            }
            $itemTemplate = $jsonParams['bx-extend-products-template'];
            $listTitle = $this->getLocalizedValue($jsonParams['bx-extend-products-title']);
            $parameter = ['name' => 'variant', 'values' => [$block->getVariantIndex()]];
            ?>
            <button id="bxOverlayExitButton" type="button">
                &#x2715;
            </button>
            <div class="bxProductsBlock">
                <div class="block-title title">
                    <strong id="block-overlay-heading"><?php echo $block->escapeHtml($listTitle); ?></strong>
                </div>
                <div class="block-content content">
                    <div class="products wrapper grid products-grid products bx-narrative"
                         data-bx-variant-uuid="<?php echo $block->getRequestUuid($this->getData("widget"));?>" data-bx-narrative-name="products-list"
                         data-bx-narrative-group-by="<?php echo $block->getRequestGroupBy();?>">
                        <?php $index = 0;?>
                        <?php foreach($block->getCollection() as $product) :?>
                            <ol class="products list items product-items bx-narrative-item" data-bx-item-id="<?php echo $product->getId();?>" data-container="product-grid">
                                <span>
                                     <?php echo $this->getLayout()->createBlock(
                                         'Boxalino\Intelligence\Block\Journey\Product\ProductView',
                                         'product_view_'. $index,
                                         ['data' => [
                                             'bx_index' => $index++,
                                             'bx_id' => $product->getId(),
                                             'bxVisualElement' => ['parameters' => [$parameter]],
                                             'bx_collection_id'=> $block->getCollectionId()]
                                         ])->setTemplate($itemTemplate)->toHtml();?>
                                </span>
                            <?php endforeach; ?>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="bxOverlayLink">
                <a class="action primary tocart" id="bxOverlayUrl">link</a>
            </div>
        </div>
    </div>
</div>
