<div class="bxOverlay bxOverlay-content" style="display: none;">
    <div class="bxOverlayProductsMain">
        <div class="bxOverlayProducts">
            <?php
            $bxVisualElement = $this->getData('bxVisualElement');
            foreach ($bxVisualElement['parameters'] as $parameter) {
                if ($parameter['name'] == 'jsParams') {
                    $jsonParams = json_decode($parameter['values'][0], true);
                }
            }
            $template_path = $jsonParams['bx-extend-products-template'];
            $productTitle = $this->getLocalizedValue($jsonParams['bx-extend-products-title']);
            $variant_id = $this->getVariantIndex();
            $product_collection = $this->bxResourceManager->getResource($variant_id, 'collection');
            $this->bxResourceManager->setResource($product_collection, $variant_id, 'collection');

            $parameter = ['name' => 'variant', 'values' => [$variant_id]];
            ?>
            <button id="bxOverlayExitButton" type="button">
                &#x2715;
            </button>
            <div class="bxProductsBlock">
                <div class="block-title title">
                    <strong id="block-overlay-heading"><?php echo $block->escapeHtml($productTitle); ?></strong>
                </div>
                <div class="block-content content">
                    <div class="products wrapper grid products-grid products">
                        <ol class="products list items product-items">
                            <?php
                            $index = 0;
                            foreach ($product_collection as $product) { ?>
                                <span>
                                 <?php $block = $this->getLayout()->createBlock(
                                     'Boxalino\Intelligence\Block\Journey\Product\ProductView',
                                     'product_view'. $index,
                                     ['data' => ['bx_index' => $index++, 'bxVisualElement' => ['parameters' => [$parameter]]]]
                                 )->setTemplate($template_path);
                                 echo $block->toHtml(); ?>
                                </span>
                            <?php }
                            ?>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="bxOverlayLink">
                <a class="action primary tocart" id="bxOverlayUrl">link</a>
            </div>
        </div>
    </div>
</div>