<div class="bxOverlay-content">
    <button class="bxOverlay" id="bxOverlayExitButton" type="button">&#x2715;</button>
    <a class="bxOverlay" id="bxOverlayUrl">
        <img class="bxOverlay" id="bxOverlayBackgroundImage">
        <img class="bxOverlay" id="bxOverlayTitleImage">
        <div class="bxOverlay" id="bxOverlayText"></div>
        <img class="bxOverlay" id="bxOverlayButton">
    </a>
</div>

