<button class="bxOverlay" id="bxOverlayExitButton<?php echo $this->getOverlayPosition(); ?>" type="button">&#x2715;</button>

<a class="bxOverlay" id="bxOverlayUrl" href="<?php echo $this->getOverlayUrl(); ?>">

  <img class="bxOverlay" id="bxOverlayBackgroundImage<?php echo $this->getOverlayPosition(); ?>" src="<?php echo $this->getOverlayBackground(); ?>">

  <img class="bxOverlay" id="bxOverlayTitleImage<?php echo $this->getOverlayPosition(); ?>" src="<?php echo $this->getOverlayTitle(); ?>">

  <div class="bxOverlay" id="bxOverlayText<?php echo $this->getOverlayPosition(); ?>"><?php echo $this->getOverlayText(); ?></div>

  <img class="bxOverlay" id="bxOverlayButton<?php echo $this->getOverlayPosition(); ?>" src="<?php echo $this->getOverlayButton(); ?>">

</a>
