<?php
    $sliderValues = $this->getSliderValues();
?>
    <script>
        require([
            'jquery',
            'nouislider',
            'mage/translate'
        ], function ($,nouislider, $t) {
            'use strict';
    
            if(document.getElementById('bxslider') !== null){
                var slider = document.getElementById('bxslider');
                var sliderMin = <?php echo isset($sliderValues[2]) ? $sliderValues[2] : "0"; ?>;
                var sliderMax = <?php echo isset($sliderValues[3]) ? $sliderValues[3] : "0"; ?>;
                nouislider.create(slider, {
                    start: [<?php echo isset($sliderValues[0]) ? $sliderValues[0] : null ?>,
                        <?php echo isset($sliderValues[1]) ? $sliderValues[1] : null; ?>],
                    connect: true,
                    behaviour: 'tap',
                    step: 1,
                    range: {
                        'min': sliderMin,
                        'max': sliderMax
                    }
                });
                
                var snapElements = [
                    document.getElementById('slider-snap-value-lower'),
                    document.getElementById('slider-snap-value-upper')
                ];
    
				var snapValues = [
                    <?php echo isset($sliderValues[0]) ? $sliderValues[0] : "0" ?>,
                    <?php echo isset($sliderValues[1]) ? $sliderValues[1] : "0" ?>
                ];
				
                slider.noUiSlider.on('update', function (values, handle) {
                    var handlename = handle == 1 ? " " + "<?php /* @escapeNotVerified */ echo __('to slider') ?>" + " " :
                    "<?php /* @escapeNotVerified */ echo __('from slider') ?>" + " ";
                    snapElements[handle].innerHTML = handlename + "<strong>" + values[handle] + "</strong>";
                });
    
                slider.noUiSlider.on('change', function (values, handle) {
					if(snapValues[handle] == values[handle]) return null;
                    var params = location.search;
                    if(values[0] == values[1])values[1]++;
                    var newSrc = values[0] + "-" + values[1];
                    var name = 'bx_discountedPrice';
                    var paramSet = name + '=' + newSrc;
                    var results = new RegExp('[\?&]' + name + '=([^&#]*)').exec(window.location.href);
                    if (results && results[1]) {
                        params = params.replace(results[1], newSrc);
                        location.search = params;
                    } else {
                        if (params) {
                            location.search = location.search + '&' + paramSet;
                        } else {
                            location.search = location.search + '?' + paramSet;
                        }
                    }
                });
            }
        });
    </script>