<?php
namespace Boxalino\Frontend\Block;

class Script extends \Boxalino\Frontend\Block\BxAbstract
{
    protected $scopeStore = \Magento\Store\Model\ScopeInterface::SCOPE_STORE;
    protected $bxSession;

    public function __construct(
        \Magento\Framework\View\Element\Context $context,
        \Boxalino\Frontend\Helper\Data $helperData,
        \Boxalino\Frontend\Model\Session $bxSession,
        array $data)
    {
        $this->bxSession = $bxSession;
        parent::__construct($context, $helperData, $data);
    }

    public function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function isEnabled()
    {
        return (bool)$this->_scopeConfig->getValue('bxGeneral/general/enabled',$this->scopeStore);
    }

    public function getScripts()
    {
        $html = '';
        $scripts = $this->bxSession->getScripts();

        foreach ($scripts as $script) {
            $html .= $script;
        }
        $this->bxSession->clearScripts();

        return $html;
    }

    public function isSearch()
    {
        $current = $this->getRequest()->getRouteName() . '/' . $this->getRequest()->getControllerName();
        return $current == 'catalogsearch/result';
    }

    public function getAccount(){
        return $this->_scopeConfig->getValue('bxGeneral/general/account_name',$this->scopeStore);
    }
}

