<?php if ($this->isActive()): ?>
    <?php echo "active"; ?>
    <div class="relaxation results">
        <?php if ($messages = $block->getNoteMessages()):?>
            <div class="message notice">
                <div>
                    <?php foreach ($messages as $message):?>
                        <?php /* @escapeNotVerified */ echo $message?><br />
                    <?php endforeach;?>
                </div>
            </div>
        <?php endif; ?>
        <?php echo $block->getProductListHtml() ?>
    </div>
<?php endif; ?>