<?php //  $session = Mage::getSingleton("core/session");
//$relax = $session->getData("relax");
//$catalogSearchHelper = $this->helper('catalogsearch');

?>
<!---->
<?php //if (count($relax) > 0): ?>
<!--    <div class="suggest">-->
<!--        <div class="header">--><?php //echo $this->__("Did you mean"); ?><!--:</div>-->
<!--        <ul class="suggestions">-->
<!--            --><?php //foreach ($relax as $r): ?>
<!--                <li>-->
<!--                    <a href="--><?php //echo $catalogSearchHelper->getResultUrl() . '?q=' . $r['href']; ?><!--">--><?php //echo $r['text'] . ' (' . $r['hits'] . ')'; ?><!--</a>-->
<!--                </li>-->
<!--            --><?php //endforeach; ?>
<!--        </ul>-->
<!--    </div>-->
<?php //endif; ?>
