<?php $filters = $this->getTopFilters(); ?>
<?php if (!empty($filters)): ?>
    <div class="top_filters" style="width:100%; margin-left:5px;">
        <?php foreach ($filters as $key => $filter): ?>
            <div class="value" style="width:33%; float:left;">
                <?php if ($filter['selected']) echo '<strong>' ?>
                <a href="<?php echo $filter['url'] ?>"><?php echo $filter['title'] . ' (' . $filter['hitCount'] . ')' ?></a>
                <?php if ($filter['selected']) echo '</strong>' ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
